analyzer:
  errors:
    sort_pub_dependencies: ignore
    lines_longer_than_80_chars: ignore
    unused_element_parameter: ignore
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
