analyzer:
  errors:
    sort_pub_dependencies: ignore
    lines_longer_than_80_chars: ignore
    unused_element_parameter: ignore
    avoid_catches_without_on_clauses: ignore
    inference_failure_on_untyped_parameter: ignore
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
