name: clone_insta
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_storage: ^13.0.1
  firebase_auth: ^6.0.2
  firebase_remote_config: ^6.0.1
  firebase_crashlytics: ^5.0.1

  #State Management
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  
  #Utils
  kartal: ^4.2.0
  easy_localization: ^3.0.8
  equatable: ^2.0.7
  intl: ^0.20.2
  hl_image_picker_ios: ^1.2.10
  get_it: ^8.2.0

  #Routing
  auto_route: ^10.1.2

  # UI
  cached_network_image: ^3.4.1
  readmore: ^3.0.0

  # Code gen
  json_annotation: ^4.9.0
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^9.0.0
  # Code gen
  json_serializable: ^6.11.0
  build_runner: ^2.7.1
  auto_route_generator: ^10.2.4
  

flutter:
  uses-material-design: true

  assets:
    - assets/images/
